spring:
  application:
    name: spring-webflux
  output:
    ansi:
      enabled: always
  r2dbc:
    url: r2dbc:pool:h2:mem://localhost/test
  sql:
    init:
      mode: embedded
      schema-locations: classpath:db-init/schema.sql
      data-locations: classpath:db-init/data.sql
#server:
#  error:
#    include-exception: true
#    include-message: always
#    include-stacktrace: always
